# -*- coding: utf-8 -*-
with open('index.html', 'r', encoding='utf-8') as f:
    lines = f.readlines()

lines[95] = '        <p class="about-ja">企業CM、ブランドムービー、企業VP、アーティストのコンサート映像、イベント映像、SNS動画、Webコンテンツ、街頭ビジョン、デジタルサイネージまで——多様なジャンルと媒体に向けた映像制作を手掛けるビジュアルディレクター。企画・演出から編集、モーショングラフィックス、デザイン、3DCG、生成AIの活用まで、映像制作の全工程を一貫して担当し、コンセプト設計から完成までをワンストップで統括。統一感と高いクオリティを兼ね備えた映像表現を実現している。<br><br>特に、モーショングラフィックスと編集を得意とし、洗練されたデザイン性と美しい動き、印象的な演出を高い次元で融合させることを強みとする。単なる映像制作にとどまらず、ブランドの魅力やメッセージを的確に伝え、観る人の感情を動かし、記憶に残る映像体験の創出を追求し続けている。クライアントの課題や目的を深く理解し、スピード感と柔軟な対応力で価値を最大化することを大切にしている。大手企業のプロモーション映像からエンターテインメント分野まで幅広い制作実績を持ち、常に新しい技術と表現を取り入れながら、成果につながる映像づくりを追求している。<br><br>「映像には、人を動かす力がある。」<br>私はその力を信じて、すべての映像と日々向き合っています。ブランドの想いを、アーティストの熱量を、企業のメッセージを——映像という表現に乗せて、観た人の心に確かな痕跡を残すこと。それが、私の使命です。あなたのプロジェクトに、一緒に命を吹き込みませんか。</p>\n'

lines[96] = '        <p class="about-en">From corporate commercials, brand videos, corporate promotional videos, artist concert footage, event videos, social media videos, web content, street-side video displays, to digital signage—a visual director who handles video production across a wide range of genres and media. From planning and direction to editing, motion graphics, design, 3D CG, and the use of generative AI, they oversee the entire video production process end-to-end, managing everything from concept development to completion as a one-stop service. They deliver video content that combines a sense of unity with high quality.<br><br>In particular, they specialize in motion graphics and editing, with a strength in seamlessly blending sophisticated design, beautiful movement, and striking direction at a high level. Going beyond mere video production, we continually strive to create memorable viewing experiences that accurately convey a brand\'s appeal and message, evoke emotion in the viewer, and leave a lasting impression. We place great importance on deeply understanding our clients\' challenges and objectives, and on maximizing value through a sense of urgency and flexible responsiveness. With a wide range of production experience—from promotional videos for major corporations to the entertainment sector—we constantly incorporate new technologies and forms of expression while pursuing video production that delivers tangible results.<br><br>"Video has the power to move people."<br>I believe in that power and approach every video project with that conviction every day. Whether it\'s a brand\'s vision, an artist\'s passion, or a company\'s message—I strive to convey it through the medium of video, leaving a lasting impression on the hearts of viewers. That is my mission. Why not join me in breathing life into your project?</p>\n'

lines[109] = '        <p class="about-ja">目を奪われるような鮮烈な色彩と、唯一無二の形と繊維が織りなす立体的な独自の世界——それは、既存のあらゆるアートの定義を超え、絵画でも彫刻でもない。既存のどんな言葉にも属さない、まったく新しい芸術の形を生み出すアーティスト。<br><br>まるで生きているかのような鮮やかさの中に、触れたくなるほどの立体感と深い奥行きを宿した作品たちは、日々新たな輝きと活力に満ちた希望のエネルギーを内側に湛えている。単なる「視覚的な美しさ」にとどまらず、鑑賞者の心に深い感動を刻み、魂を揺さぶる体験をもたらす——それが、彼の作品が持つ本質的な力である。その創作のアプローチは、これまでの芸術の枠組みそのものへの挑戦である。未知の領域を探索し続けながら、3DCGソフトウェアや3Dプリンターといった最先端の技術も積極的に取り入れ、素材と手法の垣根を超えた表現を次々と具現化。革新的なアプローチと明確なビジョンが、作品に唯一無二の独自性と圧倒的な存在感を与えている。こうして生み出される一つひとつの作品は、比類なき独自のデザインと革新的なアイデアが融合し、観る者の想像を遥かに超えた世界へと誘う。<br><br>「誰も見たことのないものを、この手で創る。」<br>その信念だけを羅針盤に、私は今日も新たな扉を叩き続ける。作品の世界はまだまだ続いています。別の角度からの詳細や、数多くの作品——その先はInstagramで！ぜひ、お気軽にフォローもしてください！</p>\n'

lines[110] = '        <p class="about-en">A unique, three-dimensional world woven from eye-catching, vivid colors, one-of-a-kind shapes, and fibers—it transcends all existing definitions of art and is neither painting nor sculpture. This artist creates an entirely new form of art that defies any existing terminology.<br><br>Amid a vividness that seems almost alive, these works possess a three-dimensional quality and profound depth that make you want to touch them; they are filled with the energy of hope, brimming with fresh radiance and vitality every day. Going beyond mere "visual beauty," they etch a deep emotional impact on the viewer\'s heart and deliver an experience that stirs the soul—that is the essential power of his work. His creative approach is a challenge to the very framework of art as we know it. While continuing to explore uncharted territories, he actively incorporates cutting-edge technologies such as 3DCG software and 3D printers, bringing to life one expression after another that transcends the boundaries of materials and techniques. His innovative approach and clear vision endow his works with unparalleled originality and an overwhelming presence. Each piece created in this way fuses unique, one-of-a-kind designs with innovative ideas, inviting viewers into a world that far surpasses their imagination.<br><br>"I create with my own hands what no one has ever seen before."<br>Guided solely by this conviction, I continue to knock on new doors every day. The world of my work is far from over. For details from different angles and a wide range of works—and much more—check out my Instagram! Please feel free to follow me!</p>\n'

with open('index.html', 'w', encoding='utf-8') as f:
    f.writelines(lines)

with open('index.html', 'r', encoding='utf-8') as f:
    check = f.read()
print('done' if 'street-side video displays' in check else 'ERROR')
